CREATE TABLE `awardees` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`trophy` integer,
	`leagueId` integer,
	`seasonId` integer,
	`winnerId` integer,
	`desc` integer,
	`userId` text
);
--> statement-breakpoint
CREATE TABLE `divisions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`leagueId` integer,
	`name` text NOT NULL,
	`userId` text,
	`logo` text NOT NULL,
	`isActive` integer,
	`discordId` text
);
--> statement-breakpoint
CREATE TABLE `eaClubs` (
	`id` integer PRIMARY KEY NOT NULL,
	`matchId` text,
	`clubId` integer,
	`timestamp` integer,
	`score` integer,
	`scoreString` text,
	`goals` integer,
	`goalsAgainst` integer,
	`result` text,
	`shots` integer,
	`passa` integer,
	`passc` integer,
	`ppg` integer,
	`ppo` integer,
	`toa` integer,
	`garaw` integer,
	`gfraw` integer,
	`winnerByDnf` integer,
	`winnerByGoalieDnf` integer,
	`clubDivision` integer,
	`cNhlOnlineGameType` text,
	`teamSide` integer,
	`memberString` text,
	`opponentClubId` integer,
	`opponentScore` integer,
	`opponentTeamArtAbbr` text,
	`teamArtAbbr` text,
	`regionId` integer,
	`teamId` integer,
	`detailsName` text,
	`customKitIsCustomTeam` integer,
	`customKitCrestAssetId` integer,
	`customKitUseBaseAsset` integer
);
--> statement-breakpoint
CREATE TABLE `eaPlayers` (
	`id` integer PRIMARY KEY NOT NULL,
	`matchId` text,
	`clubId` integer,
	`opponentClubId` integer,
	`teamId` integer,
	`opponentTeamId` integer,
	`teamArtAbbr` text,
	`opponentTeamArtAbbr` text,
	`teamSide` integer,
	`playerId` text,
	`playername` text,
	`position` text,
	`posSorted` integer,
	`isGuest` integer,
	`player_dnf` integer,
	`removedReason` text,
	`clientPlatform` text,
	`class` text,
	`playerLevel` integer,
	`rankpoints` integer,
	`ranktierassetid` text,
	`pNhlOnlineGameType` text,
	`score` integer,
	`scoreRaw` integer,
	`scoreString` text,
	`result` text,
	`opponentScore` integer,
	`ratingDefense` text,
	`ratingOffense` text,
	`ratingTeamplay` text,
	`skgoals` integer,
	`skassists` integer,
	`skshots` integer,
	`skshotattempts` integer,
	`skshotonnetpct` text,
	`skshotpct` text,
	`skgiveaways` integer,
	`sktakeaways` integer,
	`skinterceptions` integer,
	`skhits` integer,
	`skbs` integer,
	`skdeflections` integer,
	`skpassattempts` integer,
	`skpasses` integer,
	`skpasspct` text,
	`skfol` integer,
	`skfow` integer,
	`skfopct` text,
	`skpkclearzone` integer,
	`skplusmin` integer,
	`skpim` integer,
	`skpenaltiesdrawn` integer,
	`skpossession` integer,
	`skppg` integer,
	`skshg` integer,
	`sksaucerpasses` integer,
	`skgwg` integer,
	`glshots` integer,
	`glsaves` integer,
	`glsavepct` text,
	`glga` integer,
	`glgaa` text,
	`gldsaves` integer,
	`glpokechecks` integer,
	`glpkclearzone` integer,
	`glbrkshots` integer,
	`glbrksaves` integer,
	`glbrksavepct` text,
	`glpensaves` integer,
	`glpenshots` integer,
	`glpensavepct` text,
	`glsoperiods` integer,
	`toi` text,
	`toiseconds` integer,
	`memberString` text
);
--> statement-breakpoint
CREATE TABLE `leagues` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`licenseId` integer,
	`name` text NOT NULL,
	`seasons` integer,
	`divisions` integer,
	`guildId` text,
	`primaryColor` text,
	`secondaryColor` text,
	`isActive` integer,
	`userId` text
);
--> statement-breakpoint
CREATE TABLE `licenses` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`isActive` integer,
	`userId` text,
	`publicKey` text
);
--> statement-breakpoint
CREATE TABLE `matchResults` (
	`id` integer PRIMARY KEY NOT NULL,
	`matchId` text,
	`leagueId` integer,
	`seasonId` integer,
	`isCustom` integer,
	`timestamp` text,
	`clubId` integer,
	`opponentClubId` integer,
	`garaw` integer,
	`gfraw` integer,
	`memberString` text,
	`score` integer,
	`opponentScore` integer,
	`teamSide` integer,
	`toa` integer,
	`winnerByDnf` integer,
	`winnerByGoalieDnf` integer,
	`goals` integer,
	`goalsAgainst` integer,
	`gameId` integer,
	`ogMatchId` text,
	`userId` text,
	`ot` integer
);
--> statement-breakpoint
CREATE TABLE `playerResults` (
	`id` text PRIMARY KEY NOT NULL,
	`leagueId` integer,
	`seasonId` integer,
	`gameId` integer,
	`matchId` text,
	`clubId` integer,
	`opponentClubId` integer,
	`teamId` integer,
	`opponentTeamId` integer,
	`teamArtAbbr` text,
	`opponentTeamArtAbbr` text,
	`teamSide` integer,
	`playerId` text,
	`playername` text,
	`position` text,
	`posSorted` integer,
	`isGuest` integer,
	`player_dnf` integer,
	`removedReason` text,
	`clientPlatform` text,
	`class` text,
	`playerLevel` integer,
	`rankpoints` integer,
	`ranktierassetid` text,
	`pNhlOnlineGameType` text,
	`score` integer,
	`scoreRaw` integer,
	`scoreString` text,
	`result` text,
	`opponentScore` integer,
	`ratingDefense` text,
	`ratingOffense` text,
	`ratingTeamplay` text,
	`skgoals` integer,
	`skassists` integer,
	`skshots` integer,
	`skshotattempts` integer,
	`skshotonnetpct` text,
	`skshotpct` text,
	`skgiveaways` integer,
	`sktakeaways` integer,
	`skinterceptions` integer,
	`skhits` integer,
	`skbs` integer,
	`skdeflections` integer,
	`skpassattempts` integer,
	`skpasses` integer,
	`skpasspct` text,
	`skfol` integer,
	`skfow` integer,
	`skfopct` text,
	`skpkclearzone` integer,
	`skplusmin` integer,
	`skpim` integer,
	`skpenaltiesdrawn` integer,
	`skpossession` integer,
	`skppg` integer,
	`skshg` integer,
	`sksaucerpasses` integer,
	`skgwg` integer,
	`glshots` integer,
	`glsaves` integer,
	`glsavepct` text,
	`glga` integer,
	`glgaa` text,
	`gldsaves` integer,
	`glpokechecks` integer,
	`glpkclearzone` integer,
	`glbrkshots` integer,
	`glbrksaves` integer,
	`glbrksavepct` text,
	`glpensaves` integer,
	`glpenshots` integer,
	`glpensavepct` text,
	`glsoperiods` integer,
	`toi` text,
	`toiseconds` integer,
	`memberString` text
);
--> statement-breakpoint
CREATE TABLE `schedules` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`leagueId` integer NOT NULL,
	`seasonId` integer NOT NULL,
	`homeId` integer NOT NULL,
	`awayId` integer NOT NULL,
	`gameTime` integer NOT NULL,
	`gameType` integer NOT NULL,
	`userId` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `seasons` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`leagueId` integer,
	`userId` text,
	`isActive` integer,
	`name` text,
	`startDate` text,
	`endDate` text,
	`registrationStart` text,
	`registrationEnd` text,
	`draftDate` text,
	`discordRole` text,
	`discordId` text
);
--> statement-breakpoint
CREATE TABLE `teams` (
	`id` text PRIMARY KEY NOT NULL,
	`leagueId` integer,
	`clubId` integer,
	`name` text NOT NULL,
	`eaName` text NOT NULL,
	`abbr` text NOT NULL,
	`logo` text NOT NULL,
	`crestAssetId` text,
	`isCustomTeam` text,
	`isActive` integer,
	`userId` text,
	`divisionId` integer,
	`logoType` integer,
	`useBaseAsset` text NOT NULL,
	`playerRole` text,
	`gmRole` text,
	`agmRole` text
);
--> statement-breakpoint
CREATE TABLE `trophies` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`leagueId` integer,
	`name` text,
	`desc` real,
	`type` integer,
	`userId` text
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` text PRIMARY KEY NOT NULL,
	`username` text,
	`global_name` text,
	`avatar` text,
	`discriminator` text,
	`email` text,
	`verified` integer,
	`locale` text,
	`mfa_enabled` integer,
	`premium_type` integer,
	`connections` blob,
	`guilds` blob,
	`customerId` text
);
